package tn.agricultureai.repository;

import tn.agricultureai.domain.model.MarketReport;
import java.time.LocalDateTime;
import java.util.*;
import java.util.stream.Collectors;

/**
 * Repository for MarketReport entities.
 * Demonstrates: Repository pattern, searching, filtering.
 *
 * @author Your Name
 */
public class ReportRepository extends InMemoryRepository<MarketReport, String> {

    @Override
    protected String extractId(MarketReport entity) {
        return entity.id();
    }

    /**
     * Find reports by type
     */
    public List<MarketReport> findByType(MarketReport.ReportType type) {
        return findBy(report -> report.reportType().equals(type));
    }

    /**
     * Find reports generated by specific LLM
     */
    public List<MarketReport> findByGenerator(String generatorName) {
        return findBy(report -> report.generatedBy().equals(generatorName));
    }

    /**
     * Find reports within date range
     */
    public List<MarketReport> findByDateRange(
            LocalDateTime fromDate,
            LocalDateTime toDate
    ) {
        return findBy(report -> {
            LocalDateTime genTime = report.generatedAt();
            return !genTime.isBefore(fromDate) && !genTime.isAfter(toDate);
        });
    }

    /**
     * Find recent reports (last N days)
     */
    public List<MarketReport> findRecentReports(int days) {
        LocalDateTime cutoff = LocalDateTime.now().minusDays(days);
        return findBy(report -> report.generatedAt().isAfter(cutoff));
    }

    /**
     * Search reports by title (case-insensitive)
     * Demonstrates: String operations in streams
     */
    public List<MarketReport> searchByTitle(String keyword) {
        String lowerKeyword = keyword.toLowerCase();
        return findBy(report ->
                report.title().toLowerCase().contains(lowerKeyword)
        );
    }

    /**
     * Search reports by content
     */
    public List<MarketReport> searchByContent(String keyword) {
        String lowerKeyword = keyword.toLowerCase();
        return findBy(report ->
                report.content().toLowerCase().contains(lowerKeyword)
        );
    }

    /**
     * Find reports with high-confidence predictions
     * Demonstrates: Nested filtering
     */
    public List<MarketReport> findHighQualityReports(double minConfidence) {
        return findBy(report -> {
            MarketReport.ReportMetadata meta = report.metadata();
            return meta != null && meta.averageConfidence() >= minConfidence;
        });
    }

    /**
     * Get report type distribution
     */
    public Map<MarketReport.ReportType, Long> getReportTypeDistribution() {
        return findAll().stream()
                .collect(Collectors.groupingBy(
                        MarketReport::reportType,
                        Collectors.counting()
                ));
    }

    /**
     * Get average confidence by report type
     */
    public Map<MarketReport.ReportType, Double> getAverageConfidenceByType() {
        List<MarketReport> reports = findAll();
        return reports.stream()
                .collect(Collectors.groupingBy(
                        MarketReport::reportType,
                        Collectors.averagingDouble((MarketReport report) -> {
                            MarketReport.ReportMetadata meta = report.metadata();
                            return meta != null ? meta.averageConfidence() : 0.0;
                        })
                ));
    }

    /**
     * Find longest reports
     */
    public List<MarketReport> findLongestReports(int n) {
        List<MarketReport> reports = findAll();
        return reports.stream()
                .sorted(Comparator.comparingInt((MarketReport report) -> {
                    MarketReport.ReportMetadata meta = report.metadata();
                    return meta != null ? meta.wordCount() : 0;
                }).reversed())
                .limit(n)
                .collect(Collectors.toList());
    }

    /**
     * Group reports by month
     */
    public Map<String, List<MarketReport>> groupByMonth() {
        return findAll().stream()
                .collect(Collectors.groupingBy(report ->
                        report.generatedAt().getYear() + "-" +
                                String.format("%02d", report.generatedAt().getMonthValue())
                ));
    }

    /**
     * Get all unique keywords from reports
     * Demonstrates: flatMap operation
     */
    public Set<String> getAllKeywords() {
        List<MarketReport> reports = findAll();
        return reports.stream()
                .filter((MarketReport report) -> report.metadata() != null)
                .filter((MarketReport report) -> report.metadata().keywords() != null)
                .flatMap((MarketReport report) -> report.metadata().keywords().stream())
                .collect(Collectors.toSet());
    }

    /**
     * Calculate report statistics
     */
    public ReportStatistics calculateStatistics() {
        List<MarketReport> allReports = findAll();
        long totalReports = allReports.size();

        DoubleSummaryStatistics confidenceStats = allReports.stream()
                .filter((MarketReport report) -> report.metadata() != null)
                .mapToDouble((MarketReport report) -> report.metadata().averageConfidence())
                .summaryStatistics();

        IntSummaryStatistics wordCountStats = allReports.stream()
                .filter((MarketReport report) -> report.metadata() != null)
                .mapToInt((MarketReport report) -> report.metadata().wordCount())
                .summaryStatistics();

        long totalPredictions = allReports.stream()
                .filter((MarketReport report) -> report.metadata() != null)
                .mapToLong((MarketReport report) -> report.metadata().totalPredictions())
                .sum();

        return new ReportStatistics(
                totalReports,
                confidenceStats.getAverage(),
                wordCountStats.getAverage(),
                totalPredictions
        );
    }

    /**
     * Record for report statistics
     */
    public record ReportStatistics(
            long totalReports,
            double averageConfidence,
            double averageWordCount,
            long totalPredictions
    ) {
        @Override
        public String toString() {
            return String.format("""
                Report Statistics:
                  Total Reports: %d
                  Average Confidence: %.2f
                  Average Word Count: %.0f
                  Total Predictions: %d
                """,
                    totalReports,
                    averageConfidence,
                    averageWordCount,
                    totalPredictions
            );
        }
    }
}